### ISSUE TITLE
Wrong showing of colors, which shouldn't be there.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-color-codes-preview#11]
After I update to the newest version of your plugin, I got false positives for colors:

![should-not-be-there](https://user-images.githubusercontent.com/795658/28817012-3438805c-76a7-11e7-8e9d-1210dc9a45ef.png)

and 

![should-not-be-there-too](https://user-images.githubusercontent.com/795658/28817022-3c11c7b6-76a7-11e7-9eff-c8274bbc2703.png)

so as you can see, the text contains white and green so it will show that, which is false. The second example is a scss variable, where another color is inside, which is linked to this ticket: #7 

Regards

Chris

**Comment by junichi11** [comment]
I know that things. So, I added the option for named colors. (It is disabled by default.) Probably, it can be improved a bit for specific languages. If you can get unexpected results at the moment, just uncheck the option.

Thanks for your understanding.

**Comment by Chris2011** [comment]
Maybe you can check whether it is a selector or a key or a value with regex. In HTML there happens to. There should be visible inside style="color: red". So I think with a regex it will work.

**Comment by Chris2011** [comment]
```
<a href="" id="jsCopyBtn" class="link">{{ 'smth.shared.copy' | translate }}</a>
```

You only check for strings/words in each line right? It will show red because of shaRED.

**Comment by junichi11** [comment]
I already wrote: "Probably, it can be improved a bit for specific languages."

**Comment by Chris2011** [comment]
Why for specific languages? It only needs to be the value, that has to be a color name, no selector, no other string, no property. Only the value. And if there is a variable like $bla-green, than it is a variable and shouldn't be used.

**Comment by junichi11** [comment]
Why cannot you wait at all?

**Comment by Chris2011** [comment]
Your initial answer, doesn't mean that you are working on it. Please be more specific at the next time. You only wrote: If you have side effects, just uncheck it. It doesn't mean, that you are working on it.

**Comment by junichi11** [comment]
I wrote "at the moment". I'm not going to work on it soon. So I didn't write details. Anyway, you should wait a bit.

**Comment by junichi11** [comment]
I've improved it a bit. Please try to test it (0.6.0.1-dev):
https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.6.0

**Comment by Chris2011** [comment]
Looks ok for me. Thx for the work :)

**Comment by junichi11** [comment]
No problem :) Thanks for your verification.
