### ISSUE TITLE
Preview for color of specified by text constant

### ISSUE THREAD

**Issue by Dezinger** [junichi11/netbeans-color-codes-preview#12]
![2017-08-04 10-20-42](https://user-images.githubusercontent.com/432272/28958486-31597684-78ff-11e7-86dc-a543ce279def.png)
![2017-08-04 10-24-50](https://user-images.githubusercontent.com/432272/28958488-3575e0ae-78ff-11e7-8deb-a05463201db2.png)

**Comment by junichi11** [comment]
I already fixed it.(see #3) However, there is a problem yet. The current implementation matches all named colors at the moment(e.g. white-space). If you can ignore it, please check Tools > Options > Miscellaneous > Color Codes Preview > Named colors.
I'm not going to fix the problem soon, so please wait a while.

Thanks.

**Comment by junichi11** [comment]
I've improved the problem a bit. see #11
