### ISSUE TITLE
does not recognize Color.decode(<hex>)

### ISSUE THREAD

**Issue by wumpz** [junichi11/netbeans-color-codes-preview#20]

**Comment by junichi11** [comment]
Yes, it is missing. Thanks!

**Comment by junichi11** [comment]
Ah, I won't add it because you can enable hex color codes. See Tools > Options >  Miscellaneous > Color Codes Preview > Hex and CSS: Regex for enabled mime-types. Please add java there (e.g. `^text/(x-)?(css|less|sass|scss|java)$`)

**Comment by wumpz** [comment]
Thx. This does it. Could you add this **|java** part to the standard configuration or document it?

**Comment by junichi11** [comment]
OK, I'll fix README.md. I'll add the NOTE about it. Thanks!
