### ISSUE TITLE
Is it working for XML based files?

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#21]
I am developping a LaF that is Synth based. The color plugin would become very handy in this context to see the colors defined.

The definition of the colors are similar not to say identical to the CSS syntax. Example

<synth>
    <color id="defaultBgColor"         value="#3A3938"/>
    <color id="defaultFgColor"         value="#CCCCCC"/>
</synth>

So I tried to add the xml mime-type:

^text/(x-)?(css|less|sass|scss|java|XML)$

It doesn't work. By the way I have no idea to determine the exact mime-type of a file in the editor... Any idea?

I'll attach the xml file so that you can have a look.

[carbonite.zip](https://github.com/junichi11/netbeans-color-codes-preview/files/3176344/carbonite.zip)

**Comment by jmborer** [comment]
After checking the source code, the answer is: not yet. It needs improvement.

**Comment by junichi11** [comment]
Please add `|.*xml`. i.e. `^text/(x-)?(css|less|sass|scss|java|.*xml)$` .

**Comment by jmborer** [comment]
It works. Well done!
