### ISSUE TITLE
Checking the "Named Colors" option makes no difference for Java files

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#22]
Checking the Options->Miscellaneous->Color Codes Preview->Color Types: Named Colors check box makes no difference: they are always shown even when unchecked.

Steps to reproduce:
1) Make sure Named Colors check box is checked
2) open Java file that contains Color.BLACK
3) The color square is present
4) Close the file
5) Uncheck Named Colors
6) Re-open the file
7) The color square is present

Product Version: Apache NetBeans IDE 11.0 (Build incubator-netbeans-release-404-on-20190319)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_191; Java HotSpot(TM) 64-Bit Server VM 25.191-b12
Runtime: Java(TM) SE Runtime Environment 1.8.0_191-b12
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)
User directory: C:\projects\.netbeans\11.0
Cache directory: C:\projects\.netbeans\cache\11.0

**Comment by jmborer** [comment]
After checking the source code, it seems that this feature only applies to CSS like files.

**Comment by junichi11** [comment]
Yes, that is the option for Hex and CSS.
