### ISSUE TITLE
Translucent (alpha) colors in Java code are not recognized

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#23]
Transparent colors are not recognized. For example the following declaration is ignored

public static final Color RED_TRANSLUCENT = new Color(165, 21, 21, 220);

Would be nice that when translucent colors are used, the background of preview could be a squared pattern.

**Comment by jmborer** [comment]
After checking the source code, in Java files only the following declarations are supported currently:
* Color.<name>
* new Color(int,int,int)

The plugin needs improvement to support additional constructors and declarations.

**Comment by junichi11** [comment]
Yes, I know it. I didn't implement it yet.

**Comment by jmborer** [comment]
May I help?

**Comment by junichi11** [comment]
Thank you, but that's OK. I'm going to do that later.

**Comment by junichi11** [comment]
Done.
