### ISSUE TITLE
Modify the colors from the preview square?

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#24]
I have created a plugin to generate "new Color" with a color chooser in Java files. 
Maybe it would make sense to merge those projects and allow to modify the colors from the preview square as well with a color chooser, no?

As we are still developing Swing applications that heavily use color, the color plugin is super useful.

**Comment by jmborer** [comment]
What do you think about my proposal? Shall I try to merge my code into the plugin?

**Comment by junichi11** [comment]
I've already done that for Hex and CSS. (You should be able to change a color with a color chooser. e.g. `#000000`) I'm going to implement that for Java Color class later as well. So, just wait.

**Comment by junichi11** [comment]
Done.

**Comment by jmborer** [comment]
Question again, do you want me to share my code with you?

![image](https://user-images.githubusercontent.com/6607350/57778269-3643ae80-7713-11e9-8bac-ab049a4145cb.png)

**Comment by junichi11** [comment]
No, I would like to avoid doing that, sorry. Thank you for being interested in this plugin.
