### ISSUE TITLE
Generate color codes via a color chooser and code generator

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-color-codes-preview#25]
**Is your feature request related to a problem? Please describe.**

Generating color codes via a color chooser and a code generator.

**Comment by junichi11** [comment]
Done.

**Comment by jmborer** [comment]
Have a look at https://github.com/javawerks/netbeans-color-code-generator.

Would be nice if you integrate the color generation code in your project. Take anything you want. I donate them to you. Let's improve your plugin. I already have other improvements in mind, but I don't know how difficult it will be to implement them.

**Comment by junichi11** [comment]
@jmborer I've already implemented the feature as code generator. Did you try using the latest version?(https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.12.1)
see : https://github.com/junichi11/netbeans-color-codes-preview#generate-color-codes
