### ISSUE TITLE
Support for css named colors

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-color-codes-preview#3]

**Comment by Chris2011** [comment]
Would be very nice.

**Comment by wernerm** [comment]
I would also love support for the named HTML colors: http://htmlcolorcodes.com/color-names/

Are there currently any plans to introduce such a feature?

**Comment by junichi11** [comment]
Fixed.

https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.6.0

Thanks.

**Comment by wernerm** [comment]
Thanks for this! 
Unfortunately, it does not seem to work in the 0.6.0 npm build at the moment for me.

**Comment by junichi11** [comment]
This feature is not available by default. So, please try to check the Options. 

See : https://github.com/junichi11/netbeans-color-codes-preview#named-colors

**Comment by wernerm** [comment]
Thank you, it works as expected!
