### ISSUE TITLE
Support all Color constructors

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#30]
Please implement all Color constructors. Not all of us use R,G,B.

**Comment by junichi11** [comment]
> Not all of us use R,G,B.

Unnecessary words.

**Comment by jmborer** [comment]
I hope you don't mean it disrespecful, since my comment is based on facts not a personal judgement... In my team, we use mainly floats, hex and HSL color declarations. They are missing currently in your great plugin. This is also the reason I proposed to help.

**Comment by junichi11** [comment]
I'm saying that you need not say "Not all of us use R,G,B.". The vice versa is also the same thing. I feel you are complaining about missing patterns. Such the comment may make someone uncomfortable. So unnecessary words.

**Comment by jmborer** [comment]
Hmm. I think we are misunderstanding each other here. My comment was not meant to be rude in any way. As the plugin essentially support RGB declared color and that we don't such declarations, I was just saying that it would me maybe more useful then you may think to support the "missing" color constructors.

**Comment by junichi11** [comment]
Yes, so you should not write such a comment to avoid misunderstanding. That's that :)
I'm going to implement them later. Thanks.

**Comment by junichi11** [comment]
Done. https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.12.3 

If you find some problems, please report them to [Issues](https://github.com/junichi11/netbeans-color-codes-preview/issues) as new issues.

#### NOTE
- Won't support new Color(float, float, float) without `f` e.g. `new Color(0.5f, 0.2f, 0);`

**Comment by junichi11** [comment]
@jmborer Could you please try using it? Please let me know whether it works fine if possible. After that, I'm going to upload the nbm to Plugin Portal. Thanks.

**Comment by jmborer** [comment]
Shall I build it from sources?

**Comment by junichi11** [comment]
Need not to do that. As wrote the above, you can use https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.12.3.

**Comment by jmborer** [comment]
I'll test.

**Comment by jmborer** [comment]
My corporate proxy doesn't allow me to download nbm from github. I'll have to compile it myself.

**Comment by junichi11** [comment]
I see. OK.

**Comment by jmborer** [comment]
After a few tests, it looks good.

**Comment by junichi11** [comment]
Thank you! I'll upload it to PP.
