### ISSUE TITLE
Color preview 2.0: improve color support in Java by using the source lexer instead of regular expressions

### ISSUE THREAD

**Issue by jmborer** [junichi11/netbeans-color-codes-preview#34]
The plugin for Java is currently based on regexp expressions. To take is big step further, it would require the plugin to use the abstract source tree (AST) provided by the source code lexer (the same that is used during completion to provide the methods, vars etc.) instead of regular expressions. This would open a whole new world for the plugin: it can then recognize Color constants or declarations of any subclass of color such as ColorUIResource.

**Comment by jmborer** [comment]
You can start looking here how to use JavaSource class:
https://platform.netbeans.org/tutorials/60/nbm-copyfqn.html

**Comment by junichi11** [comment]
Maybe, I won't do that because it's expensive to use a parser.

**Comment by jmborer** [comment]
Not sure it is so expensive. You would be just re-using something that already exists for completion for example, no?

**Comment by junichi11** [comment]
I'm not sure whether we can use the same parser result as other features. Perhaps, can't use it. If we have to use it to implement very useful features, I would use it. Otherwise, I would like to avoid using it.
