### ISSUE TITLE
does not recognize "new java.awt.Color("

### ISSUE THREAD

**Issue by ramiswailem** [junichi11/netbeans-color-codes-preview#35]
s. title
![Screen Shot 2020-01-08 at 17 02 07](https://user-images.githubusercontent.com/26059392/71994222-aa9a0780-3238-11ea-9cab-4d261f14e232.png)

**Comment by ramiswailem** [comment]
ColorUIResource too

**Comment by junichi11** [comment]
I'll fix it later.

**Comment by junichi11** [comment]
Separate `ColorUIResource` from this issue: #36

**Comment by junichi11** [comment]
@ramiswailem Please try using 0.12.3.1-dev: https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.12.3

**Comment by ramiswailem** [comment]
It works perfect for me **0.12.3.1-dev**
Thank you @junichi11
