### ISSUE TITLE
Color with the word

### ISSUE THREAD

**Issue by Tox86** [junichi11/netbeans-color-codes-preview#43]
**Describe the bug**
Colors with the word dosen't show

**Screenshots**
![image](https://user-images.githubusercontent.com/7013508/94104624-d59baa00-fe0d-11ea-9130-fadcd46ed375.png)

**Environments**
 - OS: Windows 10 Home
 - NetBeans Version: 12.1
 - Plugin Version: unknow

**Comment by junichi11** [comment]
See https://github.com/junichi11/netbeans-color-codes-preview#named-colors
