### ISSUE TITLE
not working php and javascript

### ISSUE THREAD

**Issue by dcabanillasimagtec** [junichi11/netbeans-color-codes-preview#45]
![image](https://user-images.githubusercontent.com/67656486/94217720-55765280-fea8-11ea-9ff0-1d13e7e5fe50.png)

![image](https://user-images.githubusercontent.com/67656486/94217789-7e96e300-fea8-11ea-92bf-772cdfbf6e74.png)

**Comment by junichi11** [comment]
Don't create an new issue. Your settings(mime types) are incorrect. I wrote "see #42". Did you look at it?
not `php` but `php5`, `javascript` as well. You can check it:
![nb-color-codes-preview-issue45](https://user-images.githubusercontent.com/738383/94362925-6073f180-00f9-11eb-8efa-88ddb4c894ab.png)
