### ISSUE TITLE
Error: color codes preview in an editor's sidebar not visible

### ISSUE THREAD

**Issue by sarelvdm** [junichi11/netbeans-color-codes-preview#49]
Error: color codes preview in an editor's sidebar not visible

Can you please check.. thanks

It was working in netbeans IDE 14

**Environments (please complete the following information):**
 - OS: [win 10 x64 21h2]
 - NetBeans Version: [apache NetBeans IDE 15]
 - Plugin Version: [Version: 0.13.4]

**Comment by junichi11** [comment]
@sarelvdm Please check whether View > Show Colors is checked. (I can't reproduce it...)

```
Product Version: Apache NetBeans IDE 15
Java: 11.0.16; OpenJDK 64-Bit Server VM 11.0.16+8-post-Ubuntu-0ubuntu120.04
Runtime: OpenJDK Runtime Environment 11.0.16+8-post-Ubuntu-0ubuntu120.04
System: Linux version 5.15.0-52-generic running on amd64; UTF-8;
```

**Comment by sarelvdm** [comment]
@junichi11 , Hi
If I open a CSS file, it shows the color codes, but not in a HTML / Twig file with 
<div class="top-bar py-2" id="topBar" style="background: #555">.

Tools/Options/Miscellaneous/Color Codes Preview has Hex and CSS in dropdown and it's enabled and also tick under view.

Product Version: Apache NetBeans IDE 15
Java: 19.0.1; Java HotSpot(TM) 64-Bit Server VM 19.0.1+10-21
Runtime: Java(TM) SE Runtime Environment 19.0.1+10-21
System: Windows 10 version 10.0 running on amd64; UTF-8; en_ZA (nb)
User directory: C:\Users\SarelvdM\AppData\Roaming\NetBeans\15
Cache directory: C:\Users\SarelvdM\AppData\Local\NetBeans\Cache\15

**Comment by sarelvdm** [comment]
![netbeans](https://user-images.githubusercontent.com/3070441/198243662-e0eac877-184e-4f65-bb4f-380902af202c.gif)

**Comment by sarelvdm** [comment]
![netbeans](https://user-images.githubusercontent.com/3070441/198243908-3f30be81-2151-4c89-befe-6e6e9c76cfea.gif)
Example from twig file..

**Comment by junichi11** [comment]
@sarelvdm Not a bug. You have to set the mime-type to the `Options > Miscellaneous > Color Codes Preview > Regex for enabled mime-types` for it. (text/x-twig i.e. `^text/(x-)?(css|less|sass|scss|twig)$`)

**Comment by sarelvdm** [comment]
Thank you it worked

**Comment by junichi11** [comment]
No problem :)
