### ISSUE TITLE
Please support variables from less/sass.

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-color-codes-preview#7]
Man, first of all, this is really a life saver. Big thx, I really like it. My only problem, atm is, that if I have this inside a file called _variables:

``` sass
$grey-normal: #eee;
$grey-hover: #fff;
$grey-click: #aaa;
```

everything is fine and it works, when I import this file into an other and I use this:

``` sass
background-color: $grey-normal.
```

it doesn't resolve the variable value. This would be a nice enhancement too.

Regards

Chris

**Comment by junichi11** [comment]
Hi Chris,

Now, this plugin doesn't check color values per mime-type. Search just color value literals.
So, at first this plugin has to check a mime-type, then has to check all variables whether they have a color literal using a lexer/parser for less/sass, finally has to check whether the current line has the variables if implement your request.

I'm not sure whether I can do it soon. But I understood your request.

Thanks,
Junichi

**Comment by Chris2011** [comment]
Anything new here?

**Comment by junichi11** [comment]
Fixed. https://github.com/junichi11/netbeans-color-codes-preview/releases/tag/v0.8.0

**Note:** Resolve the simplest cases only: e.g. `$green: #0f0;` Then, in this case the popup does not work. I won't fix it.
