### ISSUE TITLE
Full crash of Netbeans

### ISSUE THREAD

**Issue by Mic-HELP** [junichi11/netbeans-color-codes-preview#9]
When I add your plugin, netbeans is completely dysfunctional. Everything disappears: projects, settings, I end up with an empty window.
Details of my setup:
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Updates: NetBeans IDE is updated to version NetBeans 8.1 Patch 1
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 10 version 10.0 running on amd64; Cp1252; fr_FR (nb)

Regards
Mic

**Comment by junichi11** [comment]
I'm not sure if there is only that information. Please try checking your logs.

Thanks.

**Comment by Mic-HELP** [comment]
After installing the plugin, I have a notification: see notification_exception.txt file
[notification_exception.txt](https://github.com/junichi11/netbeans-color-codes-preview/files/180043/notification_exception.txt)

**Comment by junichi11** [comment]
Thanks!

Please check whether the jar file exists in path/to/your-home/AppData/Roaming/NetBeans/8.1/modules/com-junichi11-netbeans-modules-color-codes-preview.jar

Probably, this is not a plugin's problem.

Please try the following if possible:
- Uninstall and reinstall the plugin
- Remove your cache directory for NetBeans (See: help > About) 
- Remove your user directory for NetBeans (See: help > About)

*NOTE:* if you remove cache or user directory, your settings will be initialized and plugins are removed.

**Comment by junichi11** [comment]
BTW, Does this problem occur when you install another plugin?(without installing this plugin)

**Comment by Mic-HELP** [comment]
Thanks for the answers.

Surely there is a path problem.
I downloaded another plugin (Mind-map NB) and it did not work.

I asked to install this plugin.
Netbeans restarts. An install popup shows a progress bar. Then it indicates an error. It closes and netbeans starts normally: standard popup and program.

There is the .jar file in the directory AppData> Roaming> Netbeans> 8.1> modules. As for your plugin.
Curiously, this plugin will appear in the list of installed plugins but nothing works, of course.
I made all the different directories cleanup as you specified.

I think I will uninstall and reinstall Netbeans.
I had already installed your plugin in another computer and it worked fine.

I made this post just to let you know Netbeans does not work in case of improper installation. Perhaps a small improvement in that case ...

Best regards
Mic

**Comment by junichi11** [comment]
> Surely there is a path problem.
> I downloaded another plugin (Mind-map NB) and it did not work.

Unfortunately, I can do nothing. So, please try to report your issue to NetBeans bugzilla or NB developers  with your logs.

Probably it will be related to the following issue:
https://netbeans.org/bugzilla/show_bug.cgi?id=149833

Thanks.
